#!/usr/bin/env python3
"""Generates the Twitch Glitch logo as RGB565 C arrays for the firmware.

Geometry is the official Glitch path (same as Font Awesome 'twitch',
viewBox 0 0 512 512): outer outline polygon, inner cutout, two "eyes".

Outputs:
  ../src/assets/twitch_glitch.h   - uint16_t RGB565 arrays (48px, 84px)
  ../assets/twitch_glitch_48.png  - preview
  ../assets/twitch_glitch_84.png  - preview

Run from this directory:  python3 make_glitch.py
"""

from PIL import Image, ImageDraw

# Official Glitch geometry (viewBox 0 0 512 512), see assets/twitch_glitch.svg
OUTER = [(120.83, 0), (24.31, 91.42), (24.31, 420.58), (140.14, 420.58),
         (140.14, 512), (236.67, 420.58), (313.92, 420.58), (487.69, 256),
         (487.69, 0)]
INNER = [(449.07, 237.75), (371.85, 310.87), (294.61, 310.87),
         (227.01, 374.87), (227.01, 310.87), (140.14, 310.87),
         (140.14, 36.58), (449.07, 36.58)]
EYES = [((285.00, 103.00), (323.63, 212.75)),
        ((391.17, 103.47), (429.80, 212.75))]

PURPLE = (145, 70, 255)   # Twitch #9146FF
BG = (14, 14, 16)         # Twitch dark #0E0E10


def render(size):
    img = Image.new("RGB", (size, size), BG)
    d = ImageDraw.Draw(img)
    s = size / 512.0
    sc = lambda pts: [(x * s, y * s) for x, y in pts]
    d.polygon(sc(OUTER), fill=PURPLE)
    d.polygon(sc(INNER), fill=BG)
    for (x0, y0), (x1, y1) in EYES:
        d.rectangle([x0 * s, y0 * s, x1 * s, y1 * s], fill=BG)
    return img


def to_rgb565(img):
    px = img.load()
    w, h = img.size
    out = []
    for y in range(h):
        for x in range(w):
            r, g, b = px[x, y]
            out.append(((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3))
    return out


def emit(name, size):
    img = render(size)
    img.save(f"../assets/twitch_glitch_{size}.png")
    vals = to_rgb565(img)
    lines = [f"// Twitch Glitch {size}x{size}, RGB565 on #0E0E10. "
             f"Generated by tools/make_glitch.py - do not edit.",
             f"static const uint16_t {name}[] = {{"]
    for i in range(0, len(vals), 12):
        lines.append("    " + ", ".join(f"0x{v:04X}" for v in vals[i:i + 12]) + ",")
    lines.append("};\n")
    return "\n".join(lines)


def main():
    header = ("#pragma once\n\n#include <stdint.h>\n\n"
              + emit("twitch_glitch_48", 48)
              + "\n"
              + emit("twitch_glitch_84", 84))
    with open("../src/assets/twitch_glitch.h", "w") as f:
        f.write(header)
    print("wrote ../src/assets/twitch_glitch.h and ../assets/*.png")


if __name__ == "__main__":
    main()
