//
// TSB/3 codec conformance test — src/proto_codec.{h,cpp} against ALL TWENTY
// golden vectors of docs/PROTOCOL.md §18, plus the §17 conformance cases.
//
// The vectors are NOT transcribed here. test/test_proto_codec/vectors.h is
// generated by gen_vectors.py, which reads the specification, lifts the bytes
// out of each hex block, re-derives every field from the §6 offset tables and
// cross-checks that against the prose printed under the block. Regenerate with:
//
//   python3 test/test_proto_codec/gen_vectors.py
//       docs/PROTOCOL.md test/test_proto_codec/vectors.h
//
// Each vector is asserted in BOTH directions:
//   decode-to-fields  golden bytes -> codec -> every field equals the spec's
//   encode-to-bytes   spec's fields -> encoder -> byte-for-byte golden frame
//
// The device codec only ships encoders for the four device->relay messages, so
// the relay->device direction is re-encoded by the small payload builders in
// this file, which are written straight from the §6 tables and then measured
// against the golden bytes. A wrong offset in either the codec or a builder
// shows up as a byte mismatch, because the comparison target is the spec.
//
// §17 requires this to run under a command the repository configures, which is
// what platformio.ini's [env:native] is for (`default_envs = esp32dev` keeps
// `pio run` building the firmware alone):
//
//   ~/.platformio/penv/bin/pio test -e native
//
// It runs on the host, with no framework and no allocation beyond the stack, so
// it also compiles standalone when bisecting:
//
//   g++ -std=gnu++11 -Isrc -o /tmp/t
//       test/test_proto_codec/test_proto_codec.cpp src/proto_codec.cpp && /tmp/t
//
// A non-zero exit status is the failure signal.
//
#include "proto_codec.h"
#include "vectors.h"

#include <stdio.h>
#include <string.h>

using namespace tsb;

// ---------------------------------------------------------------------------
// Minimal harness
// ---------------------------------------------------------------------------

static int g_failures = 0;
static int g_checks = 0;
static const char *g_case = "";

#define CHECK(cond)                                                            \
  do {                                                                         \
    ++g_checks;                                                                \
    if (!(cond)) {                                                             \
      ++g_failures;                                                            \
      printf("  FAIL  %s:%d  %s\n", g_case, __LINE__, #cond);                  \
    }                                                                          \
  } while (0)

#define CHECK_U32(got, want)                                                   \
  do {                                                                         \
    ++g_checks;                                                                \
    unsigned long g_ = (unsigned long)(got), w_ = (unsigned long)(want);       \
    if (g_ != w_) {                                                            \
      ++g_failures;                                                            \
      printf("  FAIL  %s:%d  %s: got %lu (0x%lx), want %lu (0x%lx)\n", g_case, \
             __LINE__, #got, g_, g_, w_, w_);                                  \
    }                                                                          \
  } while (0)

#define CHECK_STR(got, want)                                                   \
  do {                                                                         \
    ++g_checks;                                                                \
    if (strcmp((got), (want)) != 0) {                                          \
      ++g_failures;                                                            \
      printf("  FAIL  %s:%d  %s: got \"%s\", want \"%s\"\n", g_case, __LINE__, \
             #got, (got), (want));                                             \
    }                                                                          \
  } while (0)

static void checkBytes(const uint8_t *got, const uint8_t *want, size_t n, int line) {
  ++g_checks;
  for (size_t i = 0; i < n; ++i) {
    if (got[i] != want[i]) {
      ++g_failures;
      printf("  FAIL  %s:%d  byte %u of %u: got %02x, want %02x\n", g_case, line,
             (unsigned)i, (unsigned)n, got[i], want[i]);
      return;
    }
  }
}
#define CHECK_BYTES(got, want, n) checkBytes((got), (want), (n), __LINE__)

static void testCase(const char *name) {
  g_case = name;
  printf("- %s\n", name);
}

// Vectors asserted in both directions, counted so the summary cannot lie.
static int g_vectorsDecoded = 0;
static int g_vectorsEncoded = 0;

// ---------------------------------------------------------------------------
// Relay-side payload builders, written from the §6 field tables. The device
// firmware does not need these — only the test does, to prove the bytes.
// ---------------------------------------------------------------------------

static void putU16(uint8_t *p, uint16_t v) { p[0] = (uint8_t)v; p[1] = (uint8_t)(v >> 8); }
static void putU32(uint8_t *p, uint32_t v) {
  p[0] = (uint8_t)v; p[1] = (uint8_t)(v >> 8);
  p[2] = (uint8_t)(v >> 16); p[3] = (uint8_t)(v >> 24);
}
// §9: fixed width, NUL padded, at most width-1 content bytes.
static void putStr(uint8_t *p, size_t width, const char *s) {
  memset(p, 0, width);
  size_t n = strlen(s);
  if (n > width - 1) n = width - 1;
  memcpy(p, s, n);
}

static void buildWelcomePayload(uint8_t *p, const gv::ExpWelcome &e) {
  memset(p, 0, LEN_WELCOME);
  putU32(p + 0,  e.latest_seq);
  putU32(p + 4,  e.server_time);
  putU32(p + 8,  e.session_id);
  putU16(p + 12, e.max_frame);
  putU16(p + 14, e.ping_interval_s);
  putU16(p + 16, e.idle_timeout_s);
  putU16(p + 18, e.replay_window);
  putU32(p + 20, e.caps);
}

static void buildEventPayload(uint8_t *p, const gv::ExpEvent &e) {
  memset(p, 0, LEN_EVENT);
  putU32(p + 0,  e.seq);
  putU32(p + 4,  e.ts);
  putU32(p + 8,  e.value);
  // +12..+15 reserved1: a sender MUST write four zero bytes (§6.4, §8.1).
  putU16(p + 16, e.months);
  putU16(p + 18, e.ttl_ds);
  p[20] = e.kind;
  p[21] = e.tier;
  p[22] = e.eflags;
  p[23] = 0;                       // reserved2: MUST be written as zero.
  putStr(p + 24, 48, e.actor);
  putStr(p + 72, 96, e.text);
}

static void buildStatsPayload(uint8_t *p, const gv::ExpStats &e) {
  memset(p, 0, LEN_STATS);
  putU32(p + 0,  e.viewers);
  putU32(p + 4,  e.msg_total);
  putU32(p + 8,  e.uptime_s);
  putU32(p + 12, e.followers);
  putU32(p + 16, e.subs);
  putU32(p + 20, e.server_time);
  putU32(p + 24, e.stream_started_at);
  putU16(p + 28, e.chat_rate);
  p[30] = e.live;
  p[31] = e.sflags;
}

static void buildByePayload(uint8_t *p, const gv::ExpBye &e) {
  memset(p, 0, LEN_BYE);
  putU16(p + 0, e.code);
  putU16(p + 2, e.detail);
  putU16(p + 4, e.retry_after_s);
  putU16(p + 6, e.reserved0);
  putStr(p + 8, 24, e.reason);
}

// ---------------------------------------------------------------------------
// §3, §4.2 — every golden frame is a valid frame, and its hchk is OUR hchk.
// ---------------------------------------------------------------------------

static void test_all_frames_are_valid() {
  testCase("all 20 golden frames: magic, version, hchk, length, direction");
  CHECK_U32(gv::ALL_COUNT, 20);
  for (size_t i = 0; i < gv::ALL_COUNT; ++i) {
    const gv::ExpFrame &v = gv::ALL_VECTORS[i];
    g_case = v.name;
    CHECK(v.frame[0] == MAGIC0);
    CHECK(v.frame[1] == MAGIC1);
    CHECK(v.frame[2] == VERSION);
    CHECK(v.frame[3] == v.type);
    CHECK((v.frame[6] & ~FLAG_REPLAY) == 0);      // §3.2 reserved bits are zero
    CHECK_U32(v.frame[7], headerCheck(v.frame));  // §3.1, recomputed here
    CHECK(headerIsValid(v.frame));
    CHECK_U32(v.size, HEADER_SIZE + v.length);
    CHECK_U32(baseLengthFor(v.type), v.length);

    TsbHeader h;
    CHECK(decodeHeader(v.frame, v.size, h) == DecodeResult::Ok);
    CHECK_U32(h.version, VERSION);
    CHECK_U32(h.type, v.type);
    CHECK_U32(h.length, v.length);
    CHECK_U32(h.flags, v.flags);

    // Direction partition (§6): every type is on exactly one side.
    CHECK(typeIsInbound(v.type) != typeIsOutbound(v.type));
  }
  g_case = "";
}

// ---------------------------------------------------------------------------
// V1, V2 — HELLO, device -> relay. Both directions.
// ---------------------------------------------------------------------------

static void test_hello_vectors() {
  testCase("V1, V2 HELLO: decode to fields and encode to bytes");
  CHECK_U32(gv::HELLO_COUNT, 2);
  for (size_t i = 0; i < gv::HELLO_COUNT; ++i) {
    const gv::ExpHello &e = gv::HELLO_VECTORS[i];
    g_case = e.name;

    // decode-to-fields
    TsbHello h;
    CHECK(decodeHello(e.frame + HEADER_SIZE, e.length, h) == DecodeResult::Ok);
    CHECK_U32(h.last_seq, e.last_seq);
    CHECK_U32(h.caps, e.caps);
    CHECK_U32(h.rx_max, e.rx_max);
    CHECK_U32(h.reserved0, e.reserved0);
    CHECK_STR(h.device_id, e.device_id);
    CHECK_STR(h.fw_version, e.fw_version);
    CHECK_U32(h.rx_max >= MIN_RX_MAX, 1);   // §6.1: MUST be >= 256
    ++g_vectorsDecoded;

    // A device-to-relay type arriving AT the device is §4.3 WrongDirection,
    // never corruption and never a reason to close.
    InboundFrame f;
    CHECK(decodeInbound(e.frame, e.size, f) == DecodeResult::WrongDirection);

    // encode-to-bytes, from buildHello() plus the vector's own last_seq/caps.
    TsbHello built;
    buildHello(built, e.last_seq, e.caps, e.device_id, e.fw_version);
    uint8_t out[MAX_FRAME];
    memset(out, 0xee, sizeof(out));
    EncodeResult n = encodeHello(out, sizeof(out), built);
    CHECK_U32(n, e.size);
    if (n == (EncodeResult)e.size) CHECK_BYTES(out, e.frame, e.size);
    ++g_vectorsEncoded;
  }
  g_case = "";
}

// ---------------------------------------------------------------------------
// V3 — WELCOME
// ---------------------------------------------------------------------------

static void test_welcome_vectors() {
  testCase("V3 WELCOME: decode to fields and encode to bytes");
  CHECK_U32(gv::WELCOME_COUNT, 1);
  for (size_t i = 0; i < gv::WELCOME_COUNT; ++i) {
    const gv::ExpWelcome &e = gv::WELCOME_VECTORS[i];
    g_case = e.name;

    InboundFrame f;
    CHECK(decodeInbound(e.frame, e.size, f) == DecodeResult::Ok);
    CHECK_U32(f.header.type, T_WELCOME);
    const TsbWelcome &w = f.as.welcome;
    CHECK_U32(w.latest_seq, e.latest_seq);
    CHECK_U32(w.server_time, e.server_time);
    CHECK_U32(w.session_id, e.session_id);
    CHECK_U32(w.max_frame, e.max_frame);
    CHECK_U32(w.ping_interval_s, e.ping_interval_s);
    CHECK_U32(w.idle_timeout_s, e.idle_timeout_s);
    CHECK_U32(w.replay_window, e.replay_window);
    CHECK_U32(w.caps, e.caps);
    ++g_vectorsDecoded;

    uint8_t pay[LEN_WELCOME];
    buildWelcomePayload(pay, e);
    uint8_t out[MAX_FRAME];
    memset(out, 0xee, sizeof(out));
    EncodeResult n = encodeFrame(out, sizeof(out), e.type, e.flags, pay, LEN_WELCOME);
    CHECK_U32(n, e.size);
    if (n == (EncodeResult)e.size) CHECK_BYTES(out, e.frame, e.size);
    ++g_vectorsEncoded;
  }
  g_case = "";
}

// ---------------------------------------------------------------------------
// V6 … V15 — the ten EVENT vectors, one per kind a v3 relay can emit.
// ---------------------------------------------------------------------------

static void test_event_vectors() {
  testCase("V6-V15 EVENT: decode to fields and encode to bytes, all ten kinds");
  CHECK_U32(gv::EVENT_COUNT, 10);
  uint32_t kindsSeen = 0;
  for (size_t i = 0; i < gv::EVENT_COUNT; ++i) {
    const gv::ExpEvent &e = gv::EVENT_VECTORS[i];
    g_case = e.name;

    InboundFrame f;
    CHECK(decodeInbound(e.frame, e.size, f) == DecodeResult::Ok);
    CHECK_U32(f.header.type, T_EVENT);
    CHECK_U32(f.header.flags, e.flags);
    const TsbEvent &ev = f.as.event;
    CHECK_U32(ev.seq, e.seq);
    CHECK_U32(ev.ts, e.ts);
    CHECK_U32(ev.value, e.value);
    CHECK_U32(ev.months, e.months);
    CHECK_U32(ev.ttl_ds, e.ttl_ds);
    CHECK_U32(ev.kind, e.kind);
    CHECK_U32(ev.tier, e.tier);
    CHECK_U32(ev.eflags, e.eflags);
    CHECK_U32(ev.reserved2, e.reserved2);
    CHECK_STR(ev.actor, e.actor);
    CHECK_STR(ev.text, e.text);
    CHECK(ev.seq != 0);                        // §6.4: seq 0 is illegal
    CHECK(ev.tier <= TIER_MAX);
    CHECK(ev.kind != 0x18);                    // §6.4.1: permanently reserved
    // §8.1: reserved1 and reserved2 are zero on the wire in every v3 frame, and
    // the decoder carries them through untouched.
    for (int b = 0; b < 4; ++b) {
      CHECK_U32(e.frame[HEADER_SIZE + 12 + b], 0);
      CHECK_U32(ev.reserved1[b], e.frame[HEADER_SIZE + 12 + b]);
    }
    CHECK_U32(e.frame[HEADER_SIZE + 23], 0);
    ++g_vectorsDecoded;

    if (e.kind < 32) kindsSeen |= (1u << e.kind);

    uint8_t pay[LEN_EVENT];
    buildEventPayload(pay, e);
    uint8_t out[MAX_FRAME];
    memset(out, 0xee, sizeof(out));
    EncodeResult n = encodeFrame(out, sizeof(out), e.type, e.flags, pay, LEN_EVENT);
    CHECK_U32(n, e.size);
    if (n == (EncodeResult)e.size) CHECK_BYTES(out, e.frame, e.size);
    ++g_vectorsEncoded;
  }
  g_case = "V6-V15 EVENT";
  // §18: the ten event vectors are exactly the ten kinds a v3 relay can emit.
  const uint32_t want = (1u << K_INFO) | (1u << K_STREAM_START) | (1u << K_STREAM_END)
                      | (1u << K_FOLLOW) | (1u << K_SUB) | (1u << K_GIFT)
                      | (1u << K_RAID) | (1u << K_CHAT) | (1u << K_BITS);
  // Nine distinct codes over ten vectors: CHAT appears twice (V12, V13).
  CHECK_U32(kindsSeen, want);
  g_case = "";
}

// ---------------------------------------------------------------------------
// V4, V5 — STATS live and offline
// ---------------------------------------------------------------------------

static void test_stats_vectors() {
  testCase("V4, V5 STATS: decode to fields and encode to bytes");
  CHECK_U32(gv::STATS_COUNT, 2);
  for (size_t i = 0; i < gv::STATS_COUNT; ++i) {
    const gv::ExpStats &e = gv::STATS_VECTORS[i];
    g_case = e.name;

    InboundFrame f;
    CHECK(decodeInbound(e.frame, e.size, f) == DecodeResult::Ok);
    CHECK_U32(f.header.type, T_STATS);
    const TsbStats &s = f.as.stats;
    CHECK_U32(s.viewers, e.viewers);
    CHECK_U32(s.msg_total, e.msg_total);
    CHECK_U32(s.uptime_s, e.uptime_s);
    CHECK_U32(s.followers, e.followers);      // §6.5 — decoded, and the idle
    CHECK_U32(s.subs, e.subs);                // screen is expected to draw both
    CHECK_U32(s.server_time, e.server_time);
    CHECK_U32(s.stream_started_at, e.stream_started_at);
    CHECK_U32(s.chat_rate, e.chat_rate);
    CHECK_U32(s.live, e.live);
    CHECK_U32(s.sflags, e.sflags);
    ++g_vectorsDecoded;

    uint8_t pay[LEN_STATS];
    buildStatsPayload(pay, e);
    uint8_t out[MAX_FRAME];
    memset(out, 0xee, sizeof(out));
    EncodeResult n = encodeFrame(out, sizeof(out), e.type, e.flags, pay, LEN_STATS);
    CHECK_U32(n, e.size);
    if (n == (EncodeResult)e.size) CHECK_BYTES(out, e.frame, e.size);
    ++g_vectorsEncoded;
  }
  // §6.5: msg_total survives a stream ending; the two vectors say so in bytes.
  g_case = "V4/V5 STATS";
  CHECK_U32(gv::STATS_VECTORS[0].msg_total, gv::STATS_VECTORS[1].msg_total);
  CHECK_U32(gv::STATS_VECTORS[1].live, 0);
  CHECK_U32(gv::STATS_VECTORS[1].uptime_s, 0);
  g_case = "";
}

// ---------------------------------------------------------------------------
// V16 … V19 — PING, PONG, ACK
// ---------------------------------------------------------------------------

static void test_token_vectors() {
  testCase("V16-V19 PING / PONG / ACK: decode to fields and encode to bytes");
  CHECK_U32(gv::TOKEN_COUNT, 4);
  for (size_t i = 0; i < gv::TOKEN_COUNT; ++i) {
    const gv::ExpToken &e = gv::TOKEN_VECTORS[i];
    g_case = e.name;

    TsbToken t;
    CHECK(decodeToken(e.frame + HEADER_SIZE, e.length, t) == DecodeResult::Ok);
    CHECK_U32(t.value, e.token);
    ++g_vectorsDecoded;

    InboundFrame f;
    DecodeResult r = decodeInbound(e.frame, e.size, f);
    if (typeIsInbound(e.type)) {
      CHECK(r == DecodeResult::Ok);
      CHECK_U32(f.as.token.value, e.token);
    } else {
      CHECK(r == DecodeResult::WrongDirection);
    }

    uint8_t out[MAX_FRAME];
    memset(out, 0xee, sizeof(out));
    EncodeResult n;
    switch (e.type) {
      case T_PING_DEVICE: n = encodePing(out, sizeof(out), e.token); break;
      case T_PONG_DEVICE: n = encodePong(out, sizeof(out), e.token); break;
      case T_ACK:         n = encodeAck (out, sizeof(out), e.token); break;
      default: {
        uint8_t pay[LEN_TOKEN];
        putU32(pay, e.token);
        n = encodeFrame(out, sizeof(out), e.type, e.flags, pay, LEN_TOKEN);
        break;
      }
    }
    CHECK_U32(n, e.size);
    if (n == (EncodeResult)e.size) CHECK_BYTES(out, e.frame, e.size);
    ++g_vectorsEncoded;
  }
  // §6.3: a PONG echoes the PING's token byte for byte. V16 and V17 are that
  // pair, so the four payload bytes must be identical.
  g_case = "V16/V17 ping-pong token echo";
  CHECK_BYTES(gv::PING_DEVICE + HEADER_SIZE, gv::PONG_RELAY + HEADER_SIZE, LEN_TOKEN);
  g_case = "";
}

// ---------------------------------------------------------------------------
// V20 — BYE, the frozen shape
// ---------------------------------------------------------------------------

static void test_bye_vector() {
  testCase("V20 BYE: decode to fields and encode to bytes");
  CHECK_U32(gv::BYE_COUNT, 1);
  for (size_t i = 0; i < gv::BYE_COUNT; ++i) {
    const gv::ExpBye &e = gv::BYE_VECTORS[i];
    g_case = e.name;

    InboundFrame f;
    CHECK(decodeInbound(e.frame, e.size, f) == DecodeResult::Ok);
    CHECK_U32(f.header.type, T_BYE);
    const TsbBye &b = f.as.bye;
    CHECK_U32(b.code, e.code);
    CHECK_U32(b.detail, e.detail);
    CHECK_U32(b.retry_after_s, e.retry_after_s);
    CHECK_U32(b.reserved0, e.reserved0);
    CHECK_STR(b.reason, e.reason);
    CHECK_U32(b.code, BYE_UNSUPPORTED_VERSION);
    ++g_vectorsDecoded;

    uint8_t pay[LEN_BYE];
    buildByePayload(pay, e);
    uint8_t out[MAX_FRAME];
    memset(out, 0xee, sizeof(out));
    EncodeResult n = encodeFrame(out, sizeof(out), e.type, e.flags, pay, LEN_BYE);
    CHECK_U32(n, e.size);
    if (n == (EncodeResult)e.size) CHECK_BYTES(out, e.frame, e.size);
    ++g_vectorsEncoded;
  }
  g_case = "";
}

// ---------------------------------------------------------------------------
// §8.1 — the whole point of the reserved bytes. This is the regression test for
// the decoder that used to validate and BLANK +12..+15 and +23.
// ---------------------------------------------------------------------------

static void test_reserved_bytes_are_carried_not_blanked() {
  testCase("§8.1 EVENT reserved1/reserved2 survive decode byte for byte");
  // A v4 frame as a v3 device would see it: the held-open bytes carry a real
  // ISO 4217 code and a real exponent. A v3 receiver MUST ignore them, which
  // means MUST NOT act on them — and equally MUST NOT erase them.
  uint8_t frame[sizeof(gv::EVENT_SUB)];
  memcpy(frame, gv::EVENT_SUB, sizeof(frame));
  frame[HEADER_SIZE + 12] = 'E';
  frame[HEADER_SIZE + 13] = 'U';
  frame[HEADER_SIZE + 14] = 'R';
  frame[HEADER_SIZE + 15] = 0x00;
  frame[HEADER_SIZE + 23] = 2;
  // The payload is not covered by hchk (§3.1), so the header is untouched.
  CHECK(headerIsValid(frame));

  InboundFrame f;
  CHECK(decodeInbound(frame, sizeof(frame), f) == DecodeResult::Ok);
  CHECK_U32(f.as.event.reserved1[0], 'E');
  CHECK_U32(f.as.event.reserved1[1], 'U');
  CHECK_U32(f.as.event.reserved1[2], 'R');
  CHECK_U32(f.as.event.reserved1[3], 0x00);
  CHECK_U32(f.as.event.reserved2, 2);
  // Everything else still decodes exactly as V8 does.
  CHECK_U32(f.as.event.seq, gv::EVENT_VECTORS[2].seq);
  CHECK_STR(f.as.event.actor, gv::EVENT_VECTORS[2].actor);

  // Bytes that are not a plausible currency code are carried just the same:
  // a v3 device has no opinion about what a v4 put there.
  uint8_t junk[sizeof(gv::EVENT_FOLLOW)];
  memcpy(junk, gv::EVENT_FOLLOW, sizeof(junk));
  junk[HEADER_SIZE + 12] = 0xff;
  junk[HEADER_SIZE + 13] = 0x01;
  junk[HEADER_SIZE + 14] = 0x7a;
  junk[HEADER_SIZE + 15] = 0x40;
  junk[HEADER_SIZE + 23] = 0xfe;
  InboundFrame g;
  CHECK(decodeInbound(junk, sizeof(junk), g) == DecodeResult::Ok);
  CHECK_U32(g.as.event.reserved1[0], 0xff);
  CHECK_U32(g.as.event.reserved1[1], 0x01);
  CHECK_U32(g.as.event.reserved1[2], 0x7a);
  CHECK_U32(g.as.event.reserved1[3], 0x40);
  CHECK_U32(g.as.event.reserved2, 0xfe);
}

// ---------------------------------------------------------------------------
// §4.3 — well framed but not usable: skip the frame, keep the link.
// ---------------------------------------------------------------------------

static void test_payload_level_problems() {
  testCase("§4.3 unknown type, wrong direction, short payload, invalid field");
  uint8_t out[MAX_FRAME];
  InboundFrame f;

  // A type a newer relay added: UnknownType, never a close.
  uint8_t pay[16];
  memset(pay, 0x5a, sizeof(pay));
  EncodeResult n = encodeFrame(out, sizeof(out), 0x2f, 0, pay, sizeof(pay));
  CHECK(n == 24);
  CHECK(decodeInbound(out, (size_t)n, f) == DecodeResult::UnknownType);

  // A device-to-relay type arriving at the device: WrongDirection.
  CHECK(decodeInbound(gv::HELLO_FRESH_BOOT, sizeof(gv::HELLO_FRESH_BOOT), f)
        == DecodeResult::WrongDirection);
  CHECK(decodeInbound(gv::ACK_DEVICE, sizeof(gv::ACK_DEVICE), f)
        == DecodeResult::WrongDirection);

  // length < base: ShortPayload. Build a 16-byte STATS.
  n = encodeFrame(out, sizeof(out), T_STATS, 0, gv::STATS_LIVE + HEADER_SIZE, 16);
  CHECK(decodeInbound(out, (size_t)n, f) == DecodeResult::ShortPayload);

  // length == 0 for a type whose base is non-zero: ShortPayload.
  n = encodeFrame(out, sizeof(out), T_EVENT, 0, 0, 0);
  CHECK(n == 8);
  CHECK(decodeInbound(out, (size_t)n, f) == DecodeResult::ShortPayload);

  // EVENT.seq == 0 is fatal to the frame (§6.4), not to the link.
  uint8_t ev[sizeof(gv::EVENT_FOLLOW)];
  memcpy(ev, gv::EVENT_FOLLOW, sizeof(ev));
  memset(ev + HEADER_SIZE, 0, 4);
  CHECK(decodeInbound(ev, sizeof(ev), f) == DecodeResult::InvalidField);
}

static void test_receiver_normalisations() {
  testCase("§6.4, §6.5 receiver normalisations: tier, ttl_ds, live, unknown kind");
  uint8_t ev[sizeof(gv::EVENT_SUB)];
  InboundFrame f;

  // tier > 4 renders no tier, and MUST NOT be passed through as Prime.
  memcpy(ev, gv::EVENT_SUB, sizeof(ev));
  ev[HEADER_SIZE + 21] = 200;
  CHECK(decodeInbound(ev, sizeof(ev), f) == DecodeResult::Ok);
  CHECK_U32(f.as.event.tier, TIER_NONE);

  // ttl_ds above 6000 is clamped, not honoured and not zeroed.
  memcpy(ev, gv::EVENT_SUB, sizeof(ev));
  ev[HEADER_SIZE + 18] = 0xff;
  ev[HEADER_SIZE + 19] = 0xff;
  CHECK(decodeInbound(ev, sizeof(ev), f) == DecodeResult::Ok);
  CHECK_U32(f.as.event.ttl_ds, TTL_DS_MAX);

  // ttl_ds == 0 stays 0: §6.4 says that means "use the receiver's per-kind
  // default", which is a renderer decision, not a codec one.
  memcpy(ev, gv::EVENT_SUB, sizeof(ev));
  ev[HEADER_SIZE + 18] = 0;
  ev[HEADER_SIZE + 19] = 0;
  CHECK(decodeInbound(ev, sizeof(ev), f) == DecodeResult::Ok);
  CHECK_U32(f.as.event.ttl_ds, 0);

  // An unknown kind decodes fine: §6.4.2 says render as INFO, never drop.
  memcpy(ev, gv::EVENT_SUB, sizeof(ev));
  ev[HEADER_SIZE + 20] = 0x19;           // a v4 HYPE_TRAIN, say
  CHECK(decodeInbound(ev, sizeof(ev), f) == DecodeResult::Ok);
  CHECK_U32(f.as.event.kind, 0x19);
  CHECK_STR(f.as.event.actor, gv::EVENT_VECTORS[2].actor);

  // 0x18 is permanently reserved but is still just an unknown kind on the wire.
  memcpy(ev, gv::EVENT_SUB, sizeof(ev));
  ev[HEADER_SIZE + 20] = 0x18;
  CHECK(decodeInbound(ev, sizeof(ev), f) == DecodeResult::Ok);
  CHECK_U32(f.as.event.kind, 0x18);

  // Unknown eflags bits are ignored, never rejected.
  memcpy(ev, gv::EVENT_SUB, sizeof(ev));
  ev[HEADER_SIZE + 22] = 0xff;
  CHECK(decodeInbound(ev, sizeof(ev), f) == DecodeResult::Ok);
  CHECK_U32(f.as.event.eflags, 0xff);

  // STATS.live: any non-zero value MUST be treated as live.
  uint8_t st[sizeof(gv::STATS_OFFLINE)];
  memcpy(st, gv::STATS_OFFLINE, sizeof(st));
  st[HEADER_SIZE + 30] = 0x7f;
  CHECK(decodeInbound(st, sizeof(st), f) == DecodeResult::Ok);
  CHECK_U32(f.as.stats.live, 1);
}

static void test_unknown_flag_bits_and_versions() {
  testCase("§3.2, §7 unknown flag bits are ignored; version is not a framing error");
  uint8_t frame[sizeof(gv::EVENT_RAID_REPLAYED)];
  memcpy(frame, gv::EVENT_RAID_REPLAYED, sizeof(frame));
  CHECK_U32(frame[6], FLAG_REPLAY);

  // Set every reserved flag bit. §3.2: ignore, never reject.
  frame[6] = 0xff;
  frame[7] = headerCheck(frame);
  InboundFrame f;
  CHECK(headerIsValid(frame));
  CHECK(decodeInbound(frame, sizeof(frame), f) == DecodeResult::Ok);
  CHECK_U32(f.header.flags, 0xff);
  CHECK_U32(f.header.flags & FLAG_REPLAY, FLAG_REPLAY);

  // §4.2: version is deliberately NOT a header validity condition. That is the
  // mechanism that lets a peer read a BYE from a peer it cannot speak to.
  uint8_t bye[sizeof(gv::BYE_VERSION_MISMATCH)];
  memcpy(bye, gv::BYE_VERSION_MISMATCH, sizeof(bye));
  bye[2] = 0x09;                       // a version this device does not speak
  bye[7] = headerCheck(bye);
  CHECK(headerIsValid(bye));
  CHECK(decodeInbound(bye, sizeof(bye), f) == DecodeResult::Ok);
  CHECK_U32(f.header.version, 0x09);   // surfaced to the session layer, not eaten
  CHECK_U32(f.as.bye.code, BYE_UNSUPPORTED_VERSION);
}

// ---------------------------------------------------------------------------
// §16 rule 2 — a longer payload from a newer peer decodes and its tail is
// ignored. No field may move.
// ---------------------------------------------------------------------------

static void test_forward_compatible_longer_payload() {
  testCase("§16 a longer EVENT from a newer relay decodes; the tail is ignored");
  uint8_t out[MAX_FRAME];
  uint8_t pay[LEN_EVENT + 40];
  memcpy(pay, gv::EVENT_BITS + HEADER_SIZE, LEN_EVENT);
  memset(pay + LEN_EVENT, 0xa5, 40);      // a v4 appendix
  EncodeResult n = encodeFrame(out, sizeof(out), T_EVENT, 0, pay, sizeof(pay));
  CHECK_U32(n, HEADER_SIZE + sizeof(pay));

  InboundFrame f;
  CHECK(decodeInbound(out, (size_t)n, f) == DecodeResult::Ok);
  const gv::ExpEvent &e = gv::EVENT_VECTORS[5];   // V11 event_bits
  CHECK_U32(f.as.event.seq, e.seq);
  CHECK_U32(f.as.event.value, e.value);
  CHECK_U32(f.as.event.kind, e.kind);
  CHECK_STR(f.as.event.actor, e.actor);
  CHECK_STR(f.as.event.text, e.text);
}

// ---------------------------------------------------------------------------
// Bounds. Every read is checked before it happens.
// ---------------------------------------------------------------------------

static void test_bounds() {
  testCase("bounds: every short buffer is refused, never over-read");
  InboundFrame f;
  for (size_t i = 0; i < gv::ALL_COUNT; ++i) {
    const gv::ExpFrame &v = gv::ALL_VECTORS[i];
    g_case = v.name;
    for (size_t n = 0; n < v.size; ++n) {
      DecodeResult r = decodeInbound(v.frame, n, f);
      CHECK(r == DecodeResult::Truncated);
    }
    CHECK(decodeInbound(0, v.size, f) == DecodeResult::Truncated);
  }
  g_case = "bounds";

  TsbEvent ev; TsbStats st; TsbWelcome we; TsbBye by; TsbToken tk; TsbHello he;
  for (size_t n = 0; n < LEN_EVENT; ++n)
    CHECK(decodeEvent(gv::EVENT_SUB + HEADER_SIZE, n, ev) == DecodeResult::ShortPayload);
  for (size_t n = 0; n < LEN_STATS; ++n)
    CHECK(decodeStats(gv::STATS_LIVE + HEADER_SIZE, n, st) == DecodeResult::ShortPayload);
  for (size_t n = 0; n < LEN_WELCOME; ++n)
    CHECK(decodeWelcome(gv::WELCOME + HEADER_SIZE, n, we) == DecodeResult::ShortPayload);
  for (size_t n = 0; n < LEN_BYE; ++n)
    CHECK(decodeBye(gv::BYE_VERSION_MISMATCH + HEADER_SIZE, n, by) == DecodeResult::ShortPayload);
  for (size_t n = 0; n < LEN_TOKEN; ++n)
    CHECK(decodeToken(gv::PING_RELAY + HEADER_SIZE, n, tk) == DecodeResult::ShortPayload);
  for (size_t n = 0; n < LEN_HELLO; ++n)
    CHECK(decodeHello(gv::HELLO_FRESH_BOOT + HEADER_SIZE, n, he) == DecodeResult::ShortPayload);

  // Encoders refuse a destination that is one byte short rather than writing.
  uint8_t small[MAX_FRAME];
  TsbHello h;
  buildHello(h, 1, CAP_ACK, "roundlcd-01", "1.0.0");
  CHECK(encodeHello(small, HEADER_SIZE + LEN_HELLO - 1, h) == ENC_ERR_CAPACITY);
  CHECK(encodeHello(small, HEADER_SIZE + LEN_HELLO, h) == (EncodeResult)(HEADER_SIZE + LEN_HELLO));
  CHECK(encodePing(small, 11, 1) == ENC_ERR_CAPACITY);
  CHECK(encodeFrame(small, sizeof(small), 0x00, 0, 0, 0) == ENC_ERR_ARG);
  CHECK(encodeFrame(small, sizeof(small), T_ACK, 0, 0, 4) == ENC_ERR_ARG);
  CHECK(encodeFrame(small, sizeof(small), T_ACK, 0, small, MAX_PAYLOAD + 1) == ENC_ERR_ARG);
  g_case = "";
}

// ---------------------------------------------------------------------------
// §9.1, §9.2 strings
// ---------------------------------------------------------------------------

static void test_strings() {
  testCase("§9.1 an unterminated wire field is terminated by US, not by them");
  uint8_t field[48];
  memset(field, 'A', sizeof(field));       // 48 content bytes, no NUL anywhere
  char dst[48];
  copyWireString(dst, field, sizeof(dst));
  CHECK_U32(strlen(dst), 47);
  CHECK_U32(dst[47], 0);

  testCase("§9.2 sender truncation cuts on a code-point boundary and marks it");
  char out48[48];
  CHECK(packWireString(out48, sizeof(out48), "short") == false);
  CHECK_STR(out48, "short");
  for (size_t i = strlen("short"); i < sizeof(out48); ++i) CHECK_U32(out48[i], 0);

  // Exactly 47 content bytes fits untruncated.
  char fits[48];
  memset(fits, 0, sizeof(fits));
  char src47[48];
  memset(src47, 'x', 47);
  src47[47] = 0;
  CHECK(packWireString(fits, sizeof(fits), src47) == false);
  CHECK_U32(strlen(fits), 47);

  // 48 content bytes does not: cut to 44 + "..." = 47, and report truncation.
  char src48[49];
  memset(src48, 'x', 48);
  src48[48] = 0;
  CHECK(packWireString(fits, sizeof(fits), src48) == true);
  CHECK_U32(strlen(fits), 47);
  CHECK_STR(fits + 44, "...");

  // A value of exactly `cap` bytes is emitted unchanged, multi-byte or not:
  // "ą" is c4 85, so "aaa" + two of them is 7 bytes against a cap of 7.
  char exact[8];
  CHECK(packWireString(exact, sizeof(exact), "aaa\xc4\x85\xc4\x85") == false);
  CHECK_U32(strlen(exact), 7);
  CHECK_STR(exact, "aaa\xc4\x85\xc4\x85");
  CHECK_U32(exact[7], 0);

  // A multi-byte code point is never cut in half. Four "ą" is 8 bytes against a
  // cap of 6, so cut starts at 3 — the middle of the second "ą" — and the
  // walk-back of §9.2 step 2 moves it to 2. The result is 5 bytes, SHORTER than
  // the cap, which §9.2 explicitly allows.
  char utf[7];
  CHECK(packWireString(utf, sizeof(utf), "\xc4\x85\xc4\x85\xc4\x85\xc4\x85") == true);
  CHECK_U32(strlen(utf), 5);
  CHECK_STR(utf, "\xc4\x85...");
  CHECK_U32(utf[6], 0);

  // The last byte of the field is always NUL, whatever happened.
  char tiny[4];
  CHECK(packWireString(tiny, sizeof(tiny), "abcdefgh") == true);
  CHECK_U32(tiny[3], 0);
  CHECK_U32(strlen(tiny), 3);

  testCase("§9.2 V13's truncated strings are what a sender would have produced");
  // V13 marks both fields truncated, and both end in "...".
  const gv::ExpEvent &v13 = gv::EVENT_VECTORS[7];
  CHECK_U32(v13.eflags, EF_TEXT_TRUNCATED | EF_ACTOR_TRUNCATED);
  CHECK_U32(strlen(v13.actor), 46);
  CHECK_U32(strlen(v13.text), 94);
  CHECK_STR(v13.actor + strlen(v13.actor) - 3, "...");
  CHECK_STR(v13.text + strlen(v13.text) - 3, "...");
  // V12 is not truncated and carries multi-byte UTF-8 verbatim (CAP_UTF8_TEXT).
  const gv::ExpEvent &v12 = gv::EVENT_VECTORS[6];
  CHECK_U32(v12.eflags, EF_CHAT_COLOUR_PRESENT);
  CHECK_U32(strlen(v12.actor), 6);     // "Paweł" — 6 bytes, 5 code points
  CHECK_U32(strlen(v12.text), 21);
}

// ---------------------------------------------------------------------------
// §4.1 FrameReader — the resumable state machine
// ---------------------------------------------------------------------------

struct Collected {
  uint8_t  type;
  uint16_t length;
  uint8_t  flags;
  uint8_t  payload[MAX_PAYLOAD];
};

// Feeds `src` through `r` in chunks of `chunk` bytes, collecting every frame.
static size_t drive(FrameReader &r, const uint8_t *src, size_t n, size_t chunk,
                    Collected *out, size_t cap) {
  size_t got = 0, off = 0;
  while (off < n && !r.isFatal()) {
    size_t take = n - off;
    if (take > chunk) take = chunk;
    size_t used = 0;
    while (used < take && !r.isFatal()) {
      used += r.feed(src + off + used, take - used);
      if (r.hasFrame()) {
        if (got < cap) {
          out[got].type   = r.header().type;
          out[got].length = r.payloadLength();
          out[got].flags  = r.header().flags;
          memcpy(out[got].payload, r.payload(), r.payloadLength());
        }
        ++got;
        r.consumeFrame();
      }
      if (used == 0) break;          // reader took nothing: avoid spinning
    }
    off += take;
  }
  return got;
}

static void test_reader_streams_all_vectors() {
  testCase("§4.1 all 20 frames back to back, at every chunk size from 1 to 64");

  uint8_t stream[4096];
  size_t total = 0;
  for (size_t i = 0; i < gv::ALL_COUNT; ++i) {
    memcpy(stream + total, gv::ALL_VECTORS[i].frame, gv::ALL_VECTORS[i].size);
    total += gv::ALL_VECTORS[i].size;
  }
  CHECK_U32(total, 2096);

  static const size_t chunks[] = { 1, 2, 3, 5, 7, 8, 9, 16, 31, 64, 256, 4096 };
  for (size_t c = 0; c < sizeof(chunks) / sizeof(chunks[0]); ++c) {
    FrameReader r;
    Collected got[32];
    size_t n = drive(r, stream, total, chunks[c], got, 32);
    CHECK_U32(n, gv::ALL_COUNT);
    CHECK(!r.isFatal());
    if (n != gv::ALL_COUNT) continue;
    for (size_t i = 0; i < gv::ALL_COUNT; ++i) {
      const gv::ExpFrame &v = gv::ALL_VECTORS[i];
      CHECK_U32(got[i].type, v.type);
      CHECK_U32(got[i].length, v.length);
      CHECK_U32(got[i].flags, v.flags);
      // The §4.1 trap: a payload assembled from `length - 8` fresh bytes plus
      // eight stale ones renders leftovers from the previous frame instead of
      // crashing. Comparing the whole payload is what catches it.
      CHECK_BYTES(got[i].payload, v.frame + HEADER_SIZE, v.length);
    }
    CHECK_U32(r.counters().framesDecoded, gv::ALL_COUNT);
    CHECK_U32(r.counters().bytesReceived, total);
    CHECK_U32(r.counters().discardedBytesTotal, 0);
  }
}

static void test_reader_resynchronises() {
  testCase("§4.4 garbage between frames costs bytes, never the connection");
  uint8_t stream[1024];
  size_t n = 0;
  // Leading junk, including bare magic bytes that do not start a frame.
  static const uint8_t junk[] = { 0x7b, 0x22, 0xa7, 0xa7, 0x53, 0x00, 0xff, 0x0a };
  memcpy(stream + n, junk, sizeof(junk)); n += sizeof(junk);
  memcpy(stream + n, gv::STATS_LIVE, sizeof(gv::STATS_LIVE)); n += sizeof(gv::STATS_LIVE);
  memcpy(stream + n, junk, sizeof(junk)); n += sizeof(junk);
  memcpy(stream + n, gv::EVENT_FOLLOW, sizeof(gv::EVENT_FOLLOW)); n += sizeof(gv::EVENT_FOLLOW);
  // A truncated frame head, then a good frame: the reader must find the good one.
  memcpy(stream + n, gv::WELCOME, 5); n += 5;
  memcpy(stream + n, gv::PING_RELAY, sizeof(gv::PING_RELAY)); n += sizeof(gv::PING_RELAY);

  for (size_t chunk = 1; chunk <= 64; chunk *= 2) {
    FrameReader r;
    Collected got[8];
    size_t frames = drive(r, stream, n, chunk, got, 8);
    CHECK_U32(frames, 3);
    CHECK_U32(r.counters().resyncEvents, 2 * sizeof(junk) + 5);
    CHECK(!r.isFatal());
    if (frames == 3) {
      CHECK_U32(got[0].type, T_STATS);
      CHECK_U32(got[1].type, T_EVENT);
      CHECK_U32(got[2].type, T_PING_RELAY);
      CHECK_BYTES(got[1].payload, gv::EVENT_FOLLOW + HEADER_SIZE, LEN_EVENT);
    }
  }

  testCase("§4.5 a stream of pure garbage blows the budget and is declared fatal");
  {
    FrameReader r;
    uint8_t g[8192];
    memset(g, 0x00, sizeof(g));            // never MAGIC0: discardedBytes path
    Collected c[2];
    size_t frames = drive(r, g, sizeof(g), 64, c, 2);
    CHECK_U32(frames, 0);
    CHECK(r.isFatal());
    CHECK(r.counters().discardedBytes >= RESYNC_MAX_BYTES);
  }
  {
    // 16 windows that start with MAGIC0 but are not valid headers: the
    // rejectedCandidates half of the budget (§4.5).
    FrameReader r;
    uint8_t g[8 * 40];
    for (size_t i = 0; i < sizeof(g); i += 8) {
      g[i] = MAGIC0; g[i+1] = MAGIC1; g[i+2] = 0x03; g[i+3] = 0x21;
      g[i+4] = 0xa8; g[i+5] = 0x00; g[i+6] = 0x00; g[i+7] = 0x00;  // bad hchk
    }
    Collected c[2];
    size_t frames = drive(r, g, sizeof(g), 64, c, 2);
    CHECK_U32(frames, 0);
    CHECK(r.isFatal());
    CHECK(r.counters().rejectedCandidates >= 1);
  }

  testCase("§4.5 a good frame resets the budget, so sparse noise never accumulates");
  {
    FrameReader r;
    uint8_t s[4096];
    size_t n2 = 0;
    for (int rep = 0; rep < 12; ++rep) {
      memset(s + n2, 0x11, 300); n2 += 300;             // 300 discarded bytes
      memcpy(s + n2, gv::PING_RELAY, sizeof(gv::PING_RELAY));
      n2 += sizeof(gv::PING_RELAY);
    }
    Collected c[16];
    size_t frames = drive(r, s, n2, 37, c, 16);
    CHECK_U32(frames, 12);                               // 3600 bytes of noise
    CHECK(!r.isFatal());                                 // but never 4096 in a row
    CHECK_U32(r.counters().discardedBytesTotal, 3600);
    CHECK_U32(r.counters().discardedBytes, 0);           // reset by the last frame
  }
}

static void test_reader_every_lead_byte() {
  testCase("every byte value is a safe lead byte for the reader");
  for (unsigned b = 0; b < 256; ++b) {
    FrameReader r;
    uint8_t s[1 + sizeof(gv::STATS_LIVE)];
    s[0] = (uint8_t)b;
    memcpy(s + 1, gv::STATS_LIVE, sizeof(gv::STATS_LIVE));
    Collected c[4];
    size_t frames = drive(r, s, sizeof(s), 1, c, 4);
    CHECK_U32(frames, 1);
    CHECK(!r.isFatal());
    if (frames == 1) {
      CHECK_U32(c[0].type, T_STATS);
      CHECK_BYTES(c[0].payload, gv::STATS_LIVE + HEADER_SIZE, LEN_STATS);
    }
  }
}

static void test_reader_counters() {
  testCase("§4.3 counters: a skipped frame is counted and the link survives");
  FrameReader r;
  uint8_t s[512];
  size_t n = 0;
  uint8_t unknown[MAX_FRAME];
  uint8_t pay[8];
  memset(pay, 0, sizeof(pay));
  EncodeResult un = encodeFrame(unknown, sizeof(unknown), 0x2e, 0, pay, sizeof(pay));
  memcpy(s + n, unknown, (size_t)un); n += (size_t)un;
  memcpy(s + n, gv::HELLO_FRESH_BOOT, sizeof(gv::HELLO_FRESH_BOOT));
  n += sizeof(gv::HELLO_FRESH_BOOT);
  memcpy(s + n, gv::STATS_LIVE, sizeof(gv::STATS_LIVE)); n += sizeof(gv::STATS_LIVE);

  size_t off = 0;
  int ok = 0;
  while (off < n && !r.isFatal()) {
    off += r.feed(s + off, n - off);
    if (r.hasFrame()) {
      InboundFrame f;
      DecodeResult d = decodeInboundPayload(r.header(), r.payload(), r.payloadLength(), f);
      r.noteDecode(d);
      if (d == DecodeResult::Ok) ++ok;
      r.consumeFrame();
    }
  }
  CHECK_U32(ok, 1);                                        // only the STATS
  CHECK_U32(r.counters().framesUnknownType, 1);
  CHECK_U32(r.counters().framesWrongDirection, 1);
  CHECK_U32(r.counters().framesDecoded, 3);                // all three were framed
  CHECK(!r.isFatal());
}

static void test_counters_survive_reconnect() {
  testCase("§14 bytesSent counts 8 + length; lifetime totals survive reset(false)");
  FrameReader r;
  r.feed(gv::STATS_LIVE, sizeof(gv::STATS_LIVE));
  CHECK(r.hasFrame());
  r.consumeFrame();
  r.noteSent(sizeof(gv::PING_DEVICE));
  r.noteSent(sizeof(gv::ACK_DEVICE));
  r.noteDropped();
  CHECK_U32(r.counters().bytesSent, 2 * (HEADER_SIZE + LEN_TOKEN));
  CHECK_U32(r.counters().framesDropped, 1);

  // A half-read frame plus a dent in the §4.5 budget, then a reconnect.
  static const uint8_t junk[] = { 0x00, 0xff };
  r.feed(junk, sizeof(junk));
  r.feed(gv::STATS_LIVE, 5);
  CHECK(r.counters().discardedBytes > 0);
  r.reset(false);
  CHECK_U32(r.counters().discardedBytes, 0);               // budget cleared
  CHECK_U32(r.counters().rejectedCandidates, 0);
  CHECK_U32(r.counters().framesDecoded, 1);                // lifetime kept
  CHECK_U32(r.counters().bytesReceived, sizeof(gv::STATS_LIVE));
  CHECK_U32(r.counters().bytesSent, 2 * (HEADER_SIZE + LEN_TOKEN));
  CHECK_U32(r.counters().framesDropped, 1);
  CHECK_U32(r.counters().discardedBytesTotal, sizeof(junk));

  // The half frame was dropped: the next whole frame decodes cleanly.
  r.feed(gv::STATS_LIVE, sizeof(gv::STATS_LIVE));
  CHECK(r.hasFrame());
  CHECK_U32(r.header().type, T_STATS);
  r.consumeFrame();

  r.reset();                                               // full wipe
  CHECK_U32(r.counters().framesDecoded, 0);
  CHECK_U32(r.counters().bytesSent, 0);
}

// ---------------------------------------------------------------------------

int main() {
  printf("TSB/3 codec vs docs/PROTOCOL.md \xc2\xa7""18 — 20 golden vectors\n\n");

  test_all_frames_are_valid();
  test_hello_vectors();
  test_welcome_vectors();
  test_stats_vectors();
  test_event_vectors();
  test_token_vectors();
  test_bye_vector();
  test_reserved_bytes_are_carried_not_blanked();
  test_payload_level_problems();
  test_receiver_normalisations();
  test_unknown_flag_bits_and_versions();
  test_forward_compatible_longer_payload();
  test_bounds();
  test_strings();
  test_reader_streams_all_vectors();
  test_reader_resynchronises();
  test_reader_every_lead_byte();
  test_reader_counters();
  test_counters_survive_reconnect();

  g_case = "coverage";
  // Every one of the twenty vectors must have been asserted in both directions.
  CHECK_U32(g_vectorsDecoded, 20);
  CHECK_U32(g_vectorsEncoded, 20);

  printf("\n%d vectors decoded to fields, %d vectors encoded to bytes\n",
         g_vectorsDecoded, g_vectorsEncoded);
  printf("%d checks, %d failures\n", g_checks, g_failures);
  return g_failures == 0 ? 0 : 1;
}
